### ISSUE TITLE
Amd 64 abort in finalizing iso

### ISSUE THREAD

**Issue by ghost** [LinuxCNC/stretch-live-build#3]
Error code :

File "/home/grotius/stretch-live-build/live-wrapper/lwr/apt_udeb.py", line 101, in download_package
pkg.version_list.sort(apt_pkg.version_compare) # pylint: disable=no-member
AttributeError: 'Package' object has no attribute 'version_list'

When doing ./do.sh the 32bit version is completed as iso. The 64bit version is stopped.
Is there a solution already?

**Comment by jepler** [comment]
Thanks for reporting this issue.  However, we are not going to continue development of stretch-live-build.
